import type { Metadata } from "next";
import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { LEGAL_LAST_UPDATED, formatLegalDate } from "@/lib/legal-dates";

export const metadata: Metadata = {
  title: "Terms of Service - Streamer Times",
  description: "Streamer Times Terms of Service. Read our terms and conditions for using the app.",
  alternates: { canonical: "/terms-of-service" },
};

const sections = [
  {
    heading: "1. Acceptance of Terms",
    paragraphs: [
      'By downloading, installing, or using the Streamer Times mobile application (the "App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App.',
    ],
  },
  {
    heading: "2. Description of Service",
    paragraphs: [
      "Streamer Times is a mobile TV guide for livestreams. The App aggregates publicly available streaming schedules from platforms such as Twitch and YouTube, and provides AI-powered predictions for when streamers may go live. The App does not host or stream any video content.",
    ],
  },
  {
    heading: "3. User Accounts",
    paragraphs: [
      "An anonymous account is created automatically when you first use the App. You may optionally upgrade to an email account or sign in with Google or Apple. You are responsible for maintaining the security of your account credentials.",
    ],
  },
  {
    heading: "4. Acceptable Use",
    paragraphs: [
      "You agree to use the App for personal, non-commercial purposes only. You may not: reverse-engineer, decompile, or disassemble the App; use automated systems or bots to access the App; attempt to interfere with the proper functioning of the App; or use the App for any unlawful purpose.",
    ],
  },
  {
    heading: "5. Intellectual Property",
    paragraphs: [
      "The App, including its design, code, and branding, is the intellectual property of the Streamer Times team. Streamer names, logos, and content belong to their respective owners. Twitch is a trademark of Twitch Interactive, Inc. YouTube is a trademark of Google LLC.",
    ],
  },
  {
    heading: "6. AI Predictions Disclaimer",
    paragraphs: [
      "Stream predictions are generated by artificial intelligence and are estimates only. We do not guarantee the accuracy of any predictions, including stream start times, durations, or content. Predictions should be used for informational purposes and not relied upon as definitive schedules.",
    ],
  },
  {
    heading: "7. Limitation of Liability",
    paragraphs: [
      'The App is provided "as is" and "as available" without warranties of any kind, either express or implied. We are not liable for any damages arising from: missed streams or incorrect predictions, service interruptions or downtime, loss of data, or any other use of or inability to use the App.',
    ],
  },
  {
    heading: "8. Termination",
    paragraphs: [
      "We reserve the right to suspend or terminate your account if you violate these Terms. You may delete your account at any time by contacting us. Upon termination, your right to use the App ceases immediately.",
    ],
  },
  {
    heading: "9. Changes to These Terms",
    paragraphs: [
      'We reserve the right to modify these Terms at any time. Changes will be reflected by updating the "Last updated" date. Your continued use of the App after changes constitutes acceptance of the updated Terms.',
    ],
  },
  {
    heading: "10. Contact Us",
    paragraphs: [
      "If you have any questions about these Terms of Service, please contact us at: StreamHub.Privacy@icloud.com",
    ],
  },
];

export default function TermsOfService() {
  return (
    <main className="mx-auto max-w-3xl px-6 py-16">
      <Link
        href="/"
        className="mb-8 inline-flex items-center gap-2 text-sm text-text-secondary transition-colors hover:text-accent-cyan"
      >
        <ArrowLeft size={16} />
        Back to Streamer Times
      </Link>

      <h1 className="mb-2 text-3xl font-bold text-text-primary">
        Terms of Service
      </h1>
      <p className="mb-12 text-sm text-text-muted">
        Last updated: {formatLegalDate(LEGAL_LAST_UPDATED["terms-of-service"])}
      </p>

      {sections.map((section) => (
        <div key={section.heading} className="mb-8">
          <h2 className="mb-3 text-lg font-semibold text-text-primary">
            {section.heading}
          </h2>
          {section.paragraphs.map((paragraph, i) => (
            <p
              key={i}
              className="mb-3 text-sm leading-relaxed text-text-secondary"
            >
              {paragraph}
            </p>
          ))}
        </div>
      ))}

      <footer className="mt-16 border-t border-divider pt-8 text-center text-sm text-text-muted">
        &copy; {new Date().getFullYear()} Streamer Times. All rights reserved.
      </footer>
    </main>
  );
}
