export { getPartnerApi } from './client';
export type {
  PartnerApiClient,
  FetchOptions,
  ListStreamersOptions,
  ListSchedulesOptions,
  ListGamesOptions,
  ListRecapsOptions,
} from './client';
export {
  PartnerApiError,
  PartnerApiAuthError,
  PartnerApiNotFoundError,
  PartnerApiQuotaError,
  PartnerApiServerError,
  PartnerApiNetworkError,
} from './errors';
export type {
  Platform,
  SlotStatus,
  ConfidenceLevel,
  PublicStreamer,
  PublicStreamSlot,
  PublicGame,
  PublicStreamHistory,
  PublicStreamHistoryVod,
  PublicStreamerStats,
  PublicStreamerStatsWeekday,
  PublicStreamerStatsCategory,
  StatsWeekday,
  Paginated,
  PaginationInfo,
  RankingMetric,
  RankingValues,
  PublicRankingEntry,
  RankingsResponse,
  RankingsPagination,
  PublicStreamerRankings,
  PublicRankingPlacement,
  PublicGamePlacement,
  GameTiming,
  TimingBestSlot,
  BestGameEntry,
  StreamerInsights,
  InsightsMedianCell,
  InsightsCategoryEntry,
  InsightsGameToTry,
  InsightsScheduleReliability,
  InsightsMonthlyTrendEntry,
  InsightsFollowerPoint,
  InsightsCategoryMarket,
  RecapKind,
  RecapHero,
  RecapHeroClip,
  RecapStreamerRef,
  RecapSection,
  PublicRecapListItem,
  PublicRecapArticle,
  RecapsListResponse,
} from './types';
